AddonId: Universal_Steam_Metadata
Packages:
  - Version: 1.5
    RequiredApiVersion: 5.6.1
    ReleaseDate: 2020-12-14
    PackageUrl: e:\Devel\PlayniteExtensions\build\Release\Universal_Steam_Metadata_1_3.pext
Changelog:
  1.5:
    - Offer all available backgrounds when downloading metadata manually (not just those based on plugin settings)
    - Metadata download fails for not released games
  1.4:
    - Added support for Playnite 8
  1.3:
    - Improved automatic metadata matching
    - Support Steam AppId when searching for a game manually
    - Support for user review score
  1.2:
    - The "name" field doesn't get updated with Steam game name
    - Steam client connection being open even if not necessary
  1.1:
    - Use "features" field instead of "tags" field for consistency with the Steam library plugin
    - Option to select specific Store screenshot